<?php

use yii\db\Migration;

/**
 * Handles the creation of table `tracking`.
 */
class m170522_041213_create_tracking_table extends Migration
{
    /**
     * @inheritdoc
     */
    public function up()
    {
        $this->createTable('{{%mts_campaign}}', [
            'id' => $this->primaryKey(),
            'slug'=>$this->string(255),
            'name'=>$this->string(255)->notNull(),
            'sourceID'=>$this->integer(11)->notNull(),
            'type'=>$this->integer(11)->notNull(),
            'bid'=>$this->double(11)->defaultValue(0)->notNull(),
            'inactive'=>$this->integer(2)->notNull()->defaultValue(0),
            'pingback'=>$this->string(255),
            'passParams'=>$this->integer(2)->notNull()->defaultValue(1),
            'c1'=>$this->string(255),
            'c2'=>$this->string(255),
            'c3'=>$this->string(255),
            'c4'=>$this->string(255),
            'c5'=>$this->string(255),
            'c6'=>$this->string(255),
            'c7'=>$this->string(255),
            'c8'=>$this->string(255),
            'c9'=>$this->string(255),
            'c10'=>$this->string(255),
            'c11'=>$this->string(255),
            'c12'=>$this->string(255),
            'c13'=>$this->string(255),
            'c14'=>$this->string(255),
            'c15'=>$this->string(255),
            'c16'=>$this->string(255),
        ]);

        $this->createTable('{{%mts_offer}}',[
            'id' => $this->primaryKey(),
            'name'=>$this->string(255)->notNull(),
            'redirectUrl'=>$this->string(255)->notNull(),
            'payout'=>$this->double(11)->notNull()->defaultValue(0),
            'networkID'=>$this->integer(11)->notNull(),
            'click'=>$this->integer(11)->notNull()->defaultValue(0),
            'cost'=>$this->double(11)->notNull()->defaultValue(0),
            'income'=>$this->double(11)->notNull()->defaultValue(0),
            'lead'=>$this->integer(11)->notNull()->defaultValue(0),
//            'weight'=>$this->integer(11)->notNull()->defaultValue(0),
//            'inactive'=>$this->integer(1)->notNull()->defaultValue(0),
        ]);

        $this->createTable('{{%mts_entry_index}}',[
            'id' => $this->primaryKey(),
            'type'=>$this->integer()->notNull(),
            'fromID'=>$this->integer()->notNull(),
            'toID'=>$this->integer()->notNull(),
            'weight'=>$this->integer()->defaultValue(0),
            'inactive'=>$this->integer(1)->notNull()->defaultValue(0),
        ]);

//        $this->createTable('{{%mts_campaign_offer_index}}',[
//            'campaignID'=>$this->integer(11),
//            'offerID'=>$this->integer(11),
//            'weight'=>$this->integer(11)->notNull()->defaultValue(0),
//        ]);

        $this->createTable('{{%mts_landingpage}}',[
            'id' => $this->primaryKey(),
            'campaignID'=>$this->integer(11)->notNull(),
            'name'=>$this->string(255)->notNull(),
            'redirectUrl'=>$this->string(255)->notNull(),
            'click'=>$this->integer(11)->notNull()->defaultValue(0),
            'cost'=>$this->double(11)->notNull()->defaultValue(0),
            'income'=>$this->double(11)->notNull()->defaultValue(0),
            'lead'=>$this->integer(11)->notNull()->defaultValue(0),
//            'weight'=>$this->integer(11)->notNull()->defaultValue(0),
//            'inactive'=>$this->integer(1)->notNull()->defaultValue(0),

        ]);
//        $this->createTable('{{%mts_campaign_landingpage_index}}',[
//            'campaignID'=>$this->integer(11),
//            'lpID'=>$this->integer(11),
//            'weight'=>$this->integer(11)->notNull()->defaultValue(0),
//        ]);
//
//        $this->createTable('{{%mts_landingpage_offer_index}}',[
//            'lpID'=>$this->integer(11)->notNull(),
//            'offerID'=>$this->integer(11)->notNull(),
//            'weight'=>$this->integer(11),
//        ]);



        $this->createTable('{{%mts_cloak}}',[
            'id' => $this->primaryKey(),
            'name'=>$this->string(255)->notNull(),
            'type'=>$this->integer(11)->notNull(),
            'rule'=>$this->text()
        ]);


        $this->createTable('{{%mts_redirect}}',[
            'id'=>$this->primaryKey(),
            'campaignID'=>$this->integer(11)->notNull(),
            'redirectType'=>$this->integer(11)->notNull(),
            'type'=>$this->string(255)->notNull(),
            'subtype'=>$this->string(255),
            'opt'=>$this->integer(11)->notNull(),
            'optValue'=>$this->string(11),
            'priority'=>$this->integer(11)->defaultValue(0)->notNull(),
            'redirectUrl'=>$this->string(255)->notNull()
        ]);

        $this->createTable('{{%mts_click}}',[
            'id' => $this->primaryKey(),
            'pid' =>$this->integer(),
            'campaignID'=>$this->integer(11),
            'type'=>$this->integer(2),
            'fromID'=>$this->integer(11),
            'toID'=>$this->integer(11),
            'channel'=>$this->integer(11),
            'cpc'=>$this->double(11)->notNull()->defaultValue(0),
            'create_at'=>$this->dateTime(),
            'conversion_at'=>$this->dateTime(),
            'isconversion'=>$this->integer()->notNull()->defaultValue(0),
            'payout'=>$this->double(11)->notNull()->defaultValue(0),
            'c1'=>$this->string(255),
            'c2'=>$this->string(255),
            'c3'=>$this->string(255),
            'c4'=>$this->string(255),
            'c5'=>$this->string(255),
            'c6'=>$this->string(255),
            'c7'=>$this->string(255),
            'c8'=>$this->string(255),
            'c9'=>$this->string(255),
            'c10'=>$this->string(255),
            'c11'=>$this->string(255),
            'c12'=>$this->string(255),
            'c13'=>$this->string(255),
            'c14'=>$this->string(255),
            'c15'=>$this->string(255),
            'c16'=>$this->string(255),
            'IP'=>$this->string(255),
            'IPINT'=>$this->bigInteger(),
            'countryCode'=>$this->string(32),
            'carrierName'=>$this->string(255),
            'brandName'=>$this->string(255),
            'modelName'=>$this->string(255),
            'deviceOS'=>$this->string(255),
            'osversion'=>$this->string(255),
            'referer'=>$this->string(1024),
            'refererDomain'=>$this->string(255),
            'browser'=>$this->string(255),
            'screenResolution'=>$this->string(255),
            'screenSize'=>$this->string(255),
            'deviceType'=>$this->integer(),
            'browserVersion'=>$this->string(255),
            'userAgent'=>$this->string(1024),
            'isp'=>$this->string(255),
            'pingbackIP'=>$this->string(255),
            'pingbackIPINT'=>$this->bigInteger(),
            'clockID'=>$this->integer(),
            'clockName'=>$this->string(255),

        ]);



        $this->createTable('{{%mts_network}}',[
            'id' => $this->primaryKey(),
            'name'=>$this->string(255)->notNull()->unique(),
            'apikey'=>$this->string(255),
            'apiurl'=>$this->string( 255),
            'website'=>$this->string(255),
            'systemType'=>$this->string(64),
        ]);

        $this->createTable('{{%mts_trafficsource}}',[
            'id' => $this->primaryKey(),
            'name'=>$this->string(255)->notNull()->unique(),
            'costType'=>$this->string(32)->notNull(),
            'c1'=>$this->string(255),
            'c2'=>$this->string(255),
            'c3'=>$this->string(255),
            'c4'=>$this->string(255),
            'c5'=>$this->string(255),
            'c6'=>$this->string(255),
            'c7'=>$this->string(255),
            'c8'=>$this->string(255),
            'c9'=>$this->string(255),
            'c10'=>$this->string(255),
            'c11'=>$this->string(255),
            'c12'=>$this->string(255),
            'c13'=>$this->string(255),
            'c14'=>$this->string(255),
            'c15'=>$this->string(255),
            'c16'=>$this->string(255),
        ]);


        $this->createTable('{{%mts_browser}}', [
            'id' => $this->primaryKey(),
            'name' =>$this->string(255)->notNull()->unique(),
        ]);
        $this->createTable('{{%mts_browserversion}}', [
            'id' => $this->primaryKey(),
            'version'=>$this->string(255),
            'browserID'=>$this->integer(11),
        ]);
        $this->createIndex('idx_browserversion_browserid_version', '{{%mts_browserversion}}',
            ['browserID','version'], true);

        $this->createTable('{{%mts_carrier}}', [
            'id' => $this->primaryKey(),
            'countryCode'=>$this->string(32),
            'name'=>$this->string(255),
        ]);
        $this->createIndex('idx_carrier_countrycode_name', '{{%mts_carrier}}',
            ['countryCode','name'], true);

        $this->createTable('{{%mts_isp}}', [
            'id' => $this->primaryKey(),
            'countryCode'=>$this->string(32),
            'name'=>$this->string(255),
        ]);
        $this->createIndex('idx_isp_countrycode_name', '{{%mts_isp}}',
            ['countryCode','name'], true);


        $this->createTable('{{%mts_continent}}', [
            'id' => $this->primaryKey(),
            'continentCode'=>$this->string(32)->notNull()->unique(),
            'name'=>$this->string(255),
        ]);


        $this->createTable('{{%mts_country}}', [
            'id' => $this->primaryKey(),
            'countryCode'=>$this->string(32)->notNull(),
            'name'=>$this->string(255),
            'continentID'=>$this->integer(11)->notNull(),
        ]);

        $this->createIndex('idx_country_countrycode_continentid', '{{%mts_country}}',
            ['continentID','countryCode'], true);

        $this->createTable('{{%mts_devicetype}}', [
            'id' => $this->primaryKey(),
            'name'=>$this->string(32)->notNull()->unique(),
        ]);

        $this->createTable('{{%mts_brand}}', [
            'id' => $this->primaryKey(),
            'name'=>$this->string(255)->notNull()->unique(),
        ]);

        $this->createTable('{{%mts_model}}',[
            'id' => $this->primaryKey(),
            'name'=>$this->string(255),
            'brandID'=>$this->integer(11),
        ]);

        $this->createIndex('idx_model_brandid_name', '{{%mts_model}}',
            ['brandID','name'], true);



        $this->createTable('{{%mts_os}}', [
            'id' => $this->primaryKey(),
            'name'=>$this->string(255)->notNull()->unique(),
        ]);

        $this->createTable('{{%mts_osversion}}', [
            'id' => $this->primaryKey(),
            'version'=>$this->string(255),
            'osID'=>$this->integer(11),
        ]);
        $this->createIndex('idx_osversion_osid_version', '{{%mts_osversion}}',
            ['osID','version'], true);

        $this->createTable('{{%mts_referer}}', [
            'id' => $this->primaryKey(),
            'name'=>$this->string(255)->notNull()->unique(),
        ]);

        $this->createTable('{{%mts_refererdomain}}', [
            'id' => $this->primaryKey(),
            'name'=>$this->string(255)->notNull()->unique(),
        ]);
        $this->createTable('{{%mts_resolution}}', [
            'id' => $this->primaryKey(),
            'name'=>$this->string(255)->notNull()->unique(),
        ]);
        $this->createTable('{{%mts_size}}', [
            'id' => $this->primaryKey(),
            'name'=>$this->string(255)->notNull()->unique(),
        ]);
        $this->createTable('{{%mts_useragent}}', [
            'id' => $this->primaryKey(),
            'name'=>$this->string(255)->notNull()->unique(),
        ]);

        $this->insert('{{%mts_continent}}', [
            'id' => 1,
            'continentCode'=>'NONE',
            'name'=>'Unknown'
        ]);

        $this->insert('{{%mts_continent}}', [
            'id' => 2,
            'continentCode'=>'AS',
            'name'=>'Asia'
        ]);

        $this->insert('{{%mts_continent}}', [
            'id' => 3,
            'continentCode'=>'EU',
            'name'=>'Europe'
        ]);

        $this->insert('{{%mts_continent}}', [
            'id' => 4,
            'continentCode'=>'NA',
            'name'=>'North America'
        ]);
        $this->insert('{{%mts_continent}}', [
            'id' => 5,
            'continentCode'=>'AF',
            'name'=>'Africa'
        ]);
        $this->insert('{{%mts_continent}}', [
            'id' => 6,
            'continentCode'=>'AN',
            'name'=>'Antarctica'
        ]);

        $this->insert('{{%mts_continent}}', [
            'id' => 7,
            'continentCode'=>'SA',
            'name'=>'South America'
        ]);

        $this->insert('{{%mts_continent}}', [
            'id' => 8,
            'continentCode'=>'OC',
            'name'=>'Oceania'
        ]);

        $this->batchInsert('{{%mts_country}}',['countryCode','name','continentID'],[
            ['A1', 'Anonymous Proxy', '1'],
            ['A2', 'Satellite Provider', '1'],
            ['O1', 'Other', '1'],
            ['AE', 'United Arab Emirates', '2'],
            ['AF', 'Afghanistan', '2'],
            ['AM', 'Armenia', '2'],
            ['AP', 'Asia/Pacific Region', '2'],
            ['AZ', 'Azerbaijan', '2'],
            ['BD', 'Bangladesh', '2'],
            ['BH', 'Bahrain', '2'],
            ['BN', 'Brunei Darussalam', '2'],
            ['BT', 'Bhutan', '2'],
            ['CC', 'Cocos (Keeling) Islands', '2'],
            ['CN', 'China', '2'],
            ['CX', 'Christmas Island', '2'],
            ['CY', 'Cyprus', '2'],
            ['GE', 'Georgia', '2'],
            ['HK', 'Hong Kong', '2'],
            ['ID', 'Indonesia', '2'],
            ['IL', 'Israel', '2'],
            ['IN', 'India', '2'],
            ['IO', 'British Indian Ocean Territory', '2'],
            ['IQ', 'Iraq', '2'],
            ['IR', 'Iran, Islamic Republic of', '2'],
            ['JO', 'Jordan', '2'],
            ['JP', 'Japan', '2'],
            ['KG', 'Kyrgyzstan', '2'],
            ['KH', 'Cambodia', '2'],
            ['KP', 'Korea, Democratic People\'s Republic of', '2'],
            ['KR', 'Korea, Republic of', '2'],
            ['KW', 'Kuwait', '2'],
            ['KZ', 'Kazakhstan', '2'],
            ['LA', 'Lao People\'s Democratic Republic', '2'],
            ['LB', 'Lebanon', '2'],
            ['LK', 'Sri Lanka', '2'],
            ['MM', 'Myanmar', '2'],
            ['MN', 'Mongolia', '2'],
            ['MO', 'Macau', '2'],
            ['MV', 'Maldives', '2'],
            ['MY', 'Malaysia', '2'],
            ['NP', 'Nepal', '2'],
            ['OM', 'Oman', '2'],
            ['PH', 'Philippines', '2'],
            ['PK', 'Pakistan', '2'],
            ['PS', 'Palestinian Territory', '2'],
            ['QA', 'Qatar', '2'],
            ['SA', 'Saudi Arabia', '2'],
            ['SG', 'Singapore', '2'],
            ['SY', 'Syrian Arab Republic', '2'],
            ['TH', 'Thailand', '2'],
            ['TJ', 'Tajikistan', '2'],
            ['TL', 'Timor-Leste', '2'],
            ['TM', 'Turkmenistan', '2'],
            ['TW', 'Taiwan', '2'],
            ['UZ', 'Uzbekistan', '2'],
            ['VN', 'Vietnam', '2'],
            ['YE', 'Yemen', '2'],
            ['AD', 'Andorra', '3'],
            ['AL', 'Albania', '3'],
            ['AT', 'Austria', '3'],
            ['AX', 'Aland Islands', '3'],
            ['BA', 'Bosnia and Herzegovina', '3'],
            ['BE', 'Belgium', '3'],
            ['BG', 'Bulgaria', '3'],
            ['BY', 'Belarus', '3'],
            ['CH', 'Switzerland', '3'],
            ['CZ', 'Czech Republic', '3'],
            ['DE', 'Germany', '3'],
            ['DK', 'Denmark', '3'],
            ['EE', 'Estonia', '3'],
            ['ES', 'Spain', '3'],
            ['EU', 'Europe', '3'],
            ['FI', 'Finland', '3'],
            ['FO', 'Faroe Islands', '3'],
            ['FR', 'France', '3'],
            ['FX', 'France, Metropolitan', '3'],
            ['GB', 'United Kingdom', '3'],
            ['GG', 'Guernsey', '3'],
            ['GI', 'Gibraltar', '3'],
            ['GR', 'Greece', '3'],
            ['HR', 'Croatia', '3'],
            ['HU', 'Hungary', '3'],
            ['IE', 'Ireland', '3'],
            ['IM', 'Isle of Man', '3'],
            ['IS', 'Iceland', '3'],
            ['IT', 'Italy', '3'],
            ['JE', 'Jersey', '3'],
            ['LI', 'Liechtenstein', '3'],
            ['LT', 'Lithuania', '3'],
            ['LU', 'Luxembourg', '3'],
            ['LV', 'Latvia', '3'],
            ['MC', 'Monaco', '3'],
            ['MD', 'Moldova, Republic of', '3'],
            ['ME', 'Montenegro', '3'],
            ['MK', 'Macedonia', '3'],
            ['MT', 'Malta', '3'],
            ['NL', 'Netherlands', '3'],
            ['NO', 'Norway', '3'],
            ['PL', 'Poland', '3'],
            ['PT', 'Portugal', '3'],
            ['RO', 'Romania', '3'],
            ['RS', 'Serbia', '3'],
            ['RU', 'Russian Federation', '3'],
            ['SE', 'Sweden', '3'],
            ['SI', 'Slovenia', '3'],
            ['SJ', 'Svalbard and Jan Mayen', '3'],
            ['SK', 'Slovakia', '3'],
            ['SM', 'San Marino', '3'],
            ['TR', 'Turkey', '3'],
            ['UA', 'Ukraine', '3'],
            ['VA', 'Holy See (Vatican City State)', '3'],
            ['AG', 'Antigua and Barbuda', '4'],
            ['AI', 'Anguilla', '4'],
            ['AN', 'Netherlands Antilles', '4'],
            ['AW', 'Aruba', '4'],
            ['BB', 'Barbados', '4'],
            ['BL', 'Saint Barthelemy', '4'],
            ['BM', 'Bermuda', '4'],
            ['BQ', 'Bonaire, Saint Eustatius and Saba', '4'],
            ['BS', 'Bahamas', '4'],
            ['BZ', 'Belize', '4'],
            ['CA', 'Canada', '4'],
            ['CR', 'Costa Rica', '4'],
            ['CU', 'Cuba', '4'],
            ['CW', 'Curacao', '4'],
            ['DM', 'Dominica', '4'],
            ['DO', 'Dominican Republic', '4'],
            ['GD', 'Grenada', '4'],
            ['GL', 'Greenland', '4'],
            ['GP', 'Guadeloupe', '4'],
            ['GT', 'Guatemala', '4'],
            ['HN', 'Honduras', '4'],
            ['HT', 'Haiti', '4'],
            ['JM', 'Jamaica', '4'],
            ['KN', 'Saint Kitts and Nevis', '4'],
            ['KY', 'Cayman Islands', '4'],
            ['LC', 'Saint Lucia', '4'],
            ['MF', 'Saint Martin', '4'],
            ['MQ', 'Martinique', '4'],
            ['MS', 'Montserrat', '4'],
            ['MX', 'Mexico', '4'],
            ['NI', 'Nicaragua', '4'],
            ['PA', 'Panama', '4'],
            ['PM', 'Saint Pierre and Miquelon', '4'],
            ['PR', 'Puerto Rico', '4'],
            ['SV', 'El Salvador', '4'],
            ['SX', 'Sint Maarten (Dutch part)', '4'],
            ['TC', 'Turks and Caicos Islands', '4'],
            ['TT', 'Trinidad and Tobago', '4'],
            ['US', 'United States', '4'],
            ['VC', 'Saint Vincent and the Grenadines', '4'],
            ['VG', 'Virgin Islands, British', '4'],
            ['VI', 'Virgin Islands, U.S.', '4'],
            ['AO', 'Angola', '5'],
            ['BF', 'Burkina Faso', '5'],
            ['BI', 'Burundi', '5'],
            ['BJ', 'Benin', '5'],
            ['BW', 'Botswana', '5'],
            ['CD', 'Congo, The Democratic Republic of the', '5'],
            ['CF', 'Central African Republic', '5'],
            ['CG', 'Congo', '5'],
            ['CI', 'Cote D\'Ivoire', '5'],
            ['CM', 'Cameroon', '5'],
            ['CV', 'Cape Verde', '5'],
            ['DJ', 'Djibouti', '5'],
            ['DZ', 'Algeria', '5'],
            ['EG', 'Egypt', '5'],
            ['EH', 'Western Sahara', '5'],
            ['ER', 'Eritrea', '5'],
            ['ET', 'Ethiopia', '5'],
            ['GA', 'Gabon', '5'],
            ['GH', 'Ghana', '5'],
            ['GM', 'Gambia', '5'],
            ['GN', 'Guinea', '5'],
            ['GQ', 'Equatorial Guinea', '5'],
            ['GW', 'Guinea-Bissau', '5'],
            ['KE', 'Kenya', '5'],
            ['KM', 'Comoros', '5'],
            ['LR', 'Liberia', '5'],
            ['LS', 'Lesotho', '5'],
            ['LY', 'Libya', '5'],
            ['MA', 'Morocco', '5'],
            ['MG', 'Madagascar', '5'],
            ['ML', 'Mali', '5'],
            ['MR', 'Mauritania', '5'],
            ['MU', 'Mauritius', '5'],
            ['MW', 'Malawi', '5'],
            ['MZ', 'Mozambique', '5'],
            ['NA', 'Namibia', '5'],
            ['NE', 'Niger', '5'],
            ['NG', 'Nigeria', '5'],
            ['RE', 'Reunion', '5'],
            ['RW', 'Rwanda', '5'],
            ['SC', 'Seychelles', '5'],
            ['SD', 'Sudan', '5'],
            ['SH', 'Saint Helena', '5'],
            ['SL', 'Sierra Leone', '5'],
            ['SN', 'Senegal', '5'],
            ['SO', 'Somalia', '5'],
            ['SS', 'South Sudan', '5'],
            ['ST', 'Sao Tome and Principe', '5'],
            ['SZ', 'Swaziland', '5'],
            ['TD', 'Chad', '5'],
            ['TG', 'Togo', '5'],
            ['TN', 'Tunisia', '5'],
            ['TZ', 'Tanzania, United Republic of', '5'],
            ['UG', 'Uganda', '5'],
            ['YT', 'Mayotte', '5'],
            ['ZA', 'South Africa', '5'],
            ['ZM', 'Zambia', '5'],
            ['ZW', 'Zimbabwe', '5'],
            ['AQ', 'Antarctica', '6'],
            ['BV', 'Bouvet Island', '6'],
            ['GS', 'South Georgia and the South Sandwich Islands', '6'],
            ['HM', 'Heard Island and McDonald Islands', '6'],
            ['TF', 'French Southern Territories', '6'],
            ['AR', 'Argentina', '7'],
            ['BO', 'Bolivia', '7'],
            ['BR', 'Brazil', '7'],
            ['CL', 'Chile', '7'],
            ['CO', 'Colombia', '7'],
            ['EC', 'Ecuador', '7'],
            ['FK', 'Falkland Islands (Malvinas)', '7'],
            ['GF', 'French Guiana', '7'],
            ['GY', 'Guyana', '7'],
            ['PE', 'Peru', '7'],
            ['PY', 'Paraguay', '7'],
            ['SR', 'Suriname', '7'],
            ['UY', 'Uruguay', '7'],
            ['VE', 'Venezuela', '7'],
            ['AS', 'American Samoa', '8'],
            ['AU', 'Australia', '8'],
            ['CK', 'Cook Islands', '8'],
            ['FJ', 'Fiji', '8'],
            ['FM', 'Micronesia, Federated States of', '8'],
            ['GU', 'Guam', '8'],
            ['KI', 'Kiribati', '8'],
            ['MH', 'Marshall Islands', '8'],
            ['MP', 'Northern Mariana Islands', '8'],
            ['NC', 'New Caledonia', '8'],
            ['NF', 'Norfolk Island', '8'],
            ['NR', 'Nauru', '8'],
            ['NU', 'Niue', '8'],
            ['NZ', 'New Zealand', '8'],
            ['PF', 'French Polynesia', '8'],
            ['PG', 'Papua New Guinea', '8'],
            ['PN', 'Pitcairn Islands', '8'],
            ['PW', 'Palau', '8'],
            ['SB', 'Solomon Islands', '8'],
            ['TK', 'Tokelau', '8'],
            ['TO', 'Tonga', '8'],
            ['TV', 'Tuvalu', '8'],
            ['UM', 'United States Minor Outlying Islands', '8'],
            ['VU', 'Vanuatu', '8'],
            ['WF', 'Wallis and Futuna', '8'],
            ['WS', 'Samoa', '8']
        ]);

        $this->batchInsert('{{%mts_brand}}',['id','name'],[
            [1, 'RIM'],
            [2, 'T-Mobile'],
            [3, 'Macintosh'],
            [4, 'Apple'],
            [5, 'Google'],
            [6, 'Samsung'],
            [7, 'Nokia'],
            [8, 'SonyEricsson'],
            [9, 'Acer'],
            [10, 'Generic'],
            [11, 'Lava'],
            [12, 'Huawei'],
            [13, 'LG'],
            [14, 'Google IPs 5'],
            [15, 'HTC'],
            [16, 'Sony'],
            [17, 'Bluecoat'],
            [18, 'Micromax'],
            [19, 'Lenovo'],
            [20, 'Diyomate'],
            [21, 'Motorola'],
            [22, 'Alcatel'],
            [23, 'THL'],
            [24, 'QMobile'],
            [25, 'HTC Corporation'],
            [26, 'Windows'],
            [27, 'APNIC 4'],
            [28, 'APNIC 2'],
            [29, 'Mozilla'],
            [30, 'Tecno'],
            [31, 'Garmin-Asus'],
            [32, 'Vodafone'],
            [33, 'ZTE'],
            [34, 'APNIC 5'],
            [35, 'Coby'],
            [36, 'GO Live'],
            [37, 'i-mobile'],
            [38, 'Oppo'],
            [39, 'Feiteng'],
            [40, 'Sunup'],
            [41, 'Jiayu'],
            [42, 'Prestigio'],
            [43, 'Karbonn'],
            [44, 'MT'],
        ]);

        $this->batchInsert('{{%mts_browser}}',['id','name'],[
            [1,'BlackBerry'],
            [2,'Android Webkit'],
            [3,'Firefox'],
            [4,'Safari'],
            [5,'Chrome Mobile'],
            [6,'Nokia BrowserNG'],
            [7,'Nokia'],
            [8,'Fennec'],
            [9,'Bluecoat'],
            [10,'Nokia Browser'],
            [11,'Chrome'],
            [12,'IEMobile'],




        ]);

        $this->batchInsert('{{%mts_browserversion}}',['id','version','browserID'],[
            [1, '4.1', '1'],
            [2, '28.0', '3'],
            [3, '7.0.2', '4'],
            [4, '6.0', '4'],
            [5, '18', '5'],
            [6, '7.2', '6'],
            [7, '7.3', '6'],
            [8, '7.2', '7'],
            [9, '7.1', '6'],
            [10, '4.0', '4'],
            [11, '7.4', '6'],
            [12, '4.13', '4'],
            [13, '7.4', '10'],
            [14, '9.0', '12'],
            [15, '33.0.1750.154', '11'],
            [16, '6', '8'],
            [17, '34.0.1847.116', '11'],


        ]);

        $this->batchInsert('{{%mts_carrier}}',['id','countryCode','name'],[
            [1,'AD','Servei de Telecomunicacions dundefinedAndorra'],
            [2,'AE','du United Arab Emirates'],
            [3,'AE','Etisalat United Arab Emirates'],
            [4,'AF','MTN (Areeba) Afghanistan'],
            [5,'AF','Roshan Afghanistan'],
            [6,'AF','Telsysint (Afghan Wireless)'],
            [7,'AL','Eagle Mobile Albania'],
            [8,'AM','ArmenTel (ARMGSM) Armenia'],
            [9,'AM','VivaCell Armenia'],
            [10,'AN','Telcell St Maarten, Netherlands Antilles'],
            [11,'AO','Unitel Angola'],
            [12,'AR','Claro Argentina'],
            [13,'AR','Nextel Argentina'],
            [14,'AR','Telecom Personal Argentina'],
            [15,'AR','Telefonica Movistar Argentina'],
            [16,'AS','ASTCA American Samoa'],
            [17,'AT','3 Austria'],
            [18,'AT','Mobilkom (A1) Austria'],
            [19,'AT','Nokia Hosting Services Austria'],
            [20,'AT','Orange (One) Austria'],
            [21,'AT','T-Mobile Austria'],
            [22,'AU','3 Australia'],
            [23,'AU','Optus Australia'],
            [24,'AU','Primus Telecom Australia'],
            [25,'AU','Telstra Australia'],
            [26,'AU','Vodafone Australia'],
            [27,'AW','Setar Aruba'],
            [28,'AZ','Azercell Azerbaijan'],
            [29,'AZ','Bakcell Azerbaijan'],
            [30,'AZ','Nar Mobile Azerfon Azerbaijan'],
            [31,'BA','BH Telecom d.d. Sarajevo'],
            [32,'BA','HT-ERONET Bosnia'],
            [33,'BA','m:tel (MOBIÂ’S) Bosnia'],
            [34,'BB','Cable & Wireless Barbados'],
            [35,'BD','AKTel Bangladesh'],
            [36,'BD','Banglalink GSM'],
            [37,'BD','Citycell Bangladesh'],
            [38,'BD','GrameenPhone Bangladesh'],
            [39,'BD','TeleTalk Bangladesh'],
            [40,'BD','Warid Bangladesh'],
            [41,'BE','BASE Belgium'],
            [42,'BE','Mobistar Belgium'],
            [43,'BE','Proximus Belgium'],
            [44,'BF','Onatel Burkina Faso'],
            [45,'BG','GLOBUL Bulgaria'],
            [46,'BG','M-Tel Bulgaria'],
            [47,'BG','vivatel Bulgaria'],
            [48,'BH','Batelco Bahrain'],
            [49,'BH','Zain (MTC Vodafone) Bahrain'],
            [50,'BJ','Glomobile Benin (GloBenin)'],
            [51,'BJ','Moov (Telecel) Benin'],
            [52,'BJ','MTN (Areeba) Benin'],
            [53,'BM','M3 Wireless Bermuda'],
            [54,'BN','B-Mobile Brunei'],
            [55,'BN','DSTCom Brunei'],
            [56,'BO','Entel Bolivia'],
            [57,'BO','Nuevatel Bolivia'],
            [58,'BO','Tigo (Telefonica/Telecel) Bolivia'],
            [59,'BR','Brasil Telecom Celular'],
            [60,'BR','Claro Brazil'],
            [61,'BR','CTBC Brazil'],
            [62,'BR','Embratel Brazil'],
            [63,'BR','Oi Brazil'],
            [64,'BR','Sercomtel Celular Brazil'],
            [65,'BR','Telemig Celular Brazil'],
            [66,'BR','TIM Brazil'],
            [67,'BR','Vivo Brazil'],
            [68,'BS','Bahamas Telecommunications Company'],
            [69,'BT','B-Mobile Bhutan'],
            [70,'BT','Tashicell Bhutan'],
            [71,'BW','Mascom Wireless Botswana'],
            [72,'BW','Orange Botswana'],
            [73,'BY','BeST Belarus'],
            [74,'BY','Mobile TeleSystems Belarus'],
            [75,'BY','Velcom Belarus'],
            [76,'CA','Bell Mobility Canada'],
            [77,'CA','MTS Allstream Canada'],
            [78,'CA','Rogers Wireless Canada'],
            [79,'CA','SaskTel Canada'],
            [80,'CA','Telus Mobility Canada'],
            [81,'CA','Virgin Mobile Canada'],
            [82,'CD','Celtel/Zain Congo (Democratic Republic)'],
            [83,'CD','Tigo (Oasis) Congo (Democratic Republic)'],
            [84,'CF','Moov Central African Republic'],
            [85,'CF','Orange Centrafrique'],
            [86,'CG','MTN Congo'],
            [87,'CG','Seamobile Europe (Congo)'],
            [88,'CG','Warid Congo'],
            [89,'CH','Orange Switzerland'],
            [90,'CH','Sunrise Switzerland'],
            [91,'CH','Swisscom Switzerland'],
            [92,'CI','KoZ (Comium Ivory Coast)'],
            [93,'CI','Moov (Atlantique Cellulaire) Cote dundefinedIvoire'],
            [94,'CI','MTN CÃ´te dundefinedIvoire'],
            [95,'CI','Orange CÃ´te dundefinedIvoire'],
            [96,'CL','Claro Chile'],
            [97,'CL','Entel Chile'],
            [98,'CL','Telefonica Chile'],
            [99,'CM','MTN Cameroon'],
            [100,'CM','Orange Cameroon'],
            [101,'CN','China Mobile'],
            [102,'CN','China Unicom'],
            [103,'CO','Comcel Colombia'],
            [104,'CO','Telefonica Colombia'],
            [105,'CO','Tigo (Colombia Movil/EPM/UNE) Colombia'],
            [106,'CR','Grupo ICE Costa Rica'],
            [107,'CU','Cubacel'],
            [108,'CV','CVMovel Cape Verde'],
            [109,'CY','Cytamobile-Vodafone Cyprus'],
            [110,'CY','MTN (Areeba) Cyprus'],
            [111,'CY','ThunderWorx Cyprus'],
            [112,'CZ','T-Mobile Czech Republic'],
            [113,'CZ','TelefÃ³nica O2 Czech Republic (Eurotel Praha)'],
            [114,'CZ','Vodafone Czech Republic'],
            [115,'DE','Debitel Germany'],
            [116,'DE','E-Plus Germany'],
            [117,'DE','O2 Germany'],
            [118,'DE','T-Mobile Germany'],
            [119,'DE','Vodafone D2 Germany'],
            [120,'DJ','Evatis (Djibouti Telecom)'],
            [121,'DK','Sonofon Denmark'],
            [122,'DK','TDC Denmark'],
            [123,'DK','Telia Denmark'],
            [124,'DO','Claro Dominican Republic'],
            [125,'DO','Orange Dominican Republic'],
            [126,'DO','Tricom/Viva (Trilogy Dominicana)'],
            [127,'DZ','Djezzy Algeria'],
            [128,'DZ','Mobilis Algeria'],
            [129,'DZ','Nedjma (Wataniya) Algeria'],
            [130,'EC','Alegro GSM Ecuador'],
            [131,'EC','Porta (AmÃ©rica MÃ³vil) Ecuador'],
            [132,'EC','Telefonica Ecuador'],
            [133,'EE','Elisa Estonia'],
            [134,'EE','EMT Estonia'],
            [135,'EE','Tele2 Estonia'],
            [136,'EG','ECMS-Mobinil Egypt'],
            [137,'EG','Etisalat Egypt'],
            [138,'EG','Vodafone Egypt'],
            [139,'ES','Amena (Orange) Spain'],
            [140,'ES','Simyo Spain'],
            [141,'ES','Telefonica (Movistar) Spain'],
            [142,'ES','Vodafone Spain'],
            [143,'ES','Yoigo (Xfera Moviles) Spain'],
            [144,'ET','Ethio-Mobile (Ethiopian Telecommunication Corporation)'],
            [145,'FI','DNA Finland'],
            [146,'FI','Elisa Finland'],
            [147,'FI','Saunalahti (Elisa) Finland'],
            [148,'FI','TeliaSonera Finland'],
            [149,'FJ','Digicel Fiji'],
            [150,'FJ','Vodafone Fiji'],
            [151,'FO','Faroese Telecom GSM Faroe Islands'],
            [152,'FR','Bouygues Telecom France'],
            [153,'FR','Orange France'],
            [154,'FR','SFR France'],
            [155,'FR','Tele2 France'],
            [156,'FR','ZeMobile (Kertel) France'],
            [157,'GA','Libertis Gabon'],
            [158,'GB','3 UK'],
            [159,'GB','Jersey Airtel GB'],
            [160,'GB','Jersey Telecom GB'],
            [161,'GB','Manx Telecom Isle of Man'],
            [162,'GB','Novarra Proxy UK'],
            [163,'GB','O2 UK'],
            [164,'GB','Orange UK'],
            [165,'GB','Research In Motion UK'],
            [166,'GB','T-Mobile UK'],
            [167,'GB','Virgin Media'],
            [168,'GB','Vodafone UK'],
            [169,'GE','Beeline Georgia'],
            [170,'GE','Geocell Georgia'],
            [171,'GE','MagtiGSM Georgia'],
            [172,'GG','Cable & Wireless Guernsey GPRS'],
            [173,'GH','MTN (Scancom) Ghana'],
            [174,'GH','One Touch Ghana'],
            [175,'GH','Tigo Ghana'],
            [176,'GH','Zain Ghana'],
            [177,'GI','Gibraltar Telecommunications'],
            [178,'GL','Tele Greenland'],
            [179,'GM','Comium Gambia'],
            [180,'GN','MTN (Areeba) Guinea-Conakry'],
            [181,'GN','Sotelgui Guinea'],
            [182,'GP','Orange Guadeloupe'],
            [183,'GQ','Orange GETESA Equatorial Guinea'],
            [184,'GR','Cosmote Greece'],
            [185,'GR','Telestet WIND Greece'],
            [186,'GR','Vodafone Greece'],
            [187,'GT','Claro (Telgua) Guatemala'],
            [188,'GT','COMCEL Guatemala'],
            [189,'GU','GuamCell'],
            [190,'GU','IT&E Wireless Guam'],
            [191,'GU','MPULSE (Teleguam) Guam'],
            [192,'GW','MTN Guinea-Bissau'],
            [193,'GY','Cellink Guayana (GT&T)'],
            [194,'HK','3 Hong Kong'],
            [195,'HK','CSL Hong Kong'],
            [196,'HK','New World Mobility Hong Kong'],
            [197,'HK','PCCW (SUNDAY) Hong Kong'],
            [198,'HK','Peoples Hong Kong'],
            [199,'HK','Smartone-Vodafone Hong Kong'],
            [200,'HN','Tigo (CELTEL, Millicom) Honduras'],
            [201,'HR','T-Mobile Croatia'],
            [202,'HR','Tele2 Croatia'],
            [203,'HR','VIPnet Croatia'],
            [204,'HT','Voila (Comcel) Haiti'],
            [205,'HU','Pannon GSM Hungary'],
            [206,'HU','T-Mobile Hungary'],
            [207,'HU','Vodafone Hungary'],
            [208,'ID','3 Indonesia'],
            [209,'ID','Bakrie Telecom Indonesia'],
            [210,'ID','Excelcomindo (XL) Indonesia'],
            [211,'ID','Mobile8 Indonesia'],
            [212,'ID','Natrindo Telecom Selular Indonesia'],
            [213,'ID','Satelindo (Indosat) Indonesia'],
            [214,'ID','Smart Telecom Indonesia'],
            [215,'ID','Telkomsel Indonesia'],
            [216,'IE','3 Ireland'],
            [217,'IE','Meteor Ireland'],
            [218,'IE','O2 Ireland'],
            [219,'IE','Vodafone Ireland'],
            [220,'IL','Cellcom Israel'],
            [221,'IL','Mirs Israel'],
            [222,'IL','Orange (Partner) Israel'],
            [223,'IL','Pelephone Israel'],
            [224,'IN','Airtel Cellular India'],
            [225,'IN','BPL India'],
            [226,'IN','BSNL India'],
            [227,'IN','Dishnet Wireless (Aircel) India'],
            [228,'IN','HFCL InfoTel India'],
            [229,'IN','Idea Cellular India'],
            [230,'IN','MTNL Mobile (Dolphin) India'],
            [231,'IN','Reliance Infocom India'],
            [232,'IN','Shyam Telelink India'],
            [233,'IN','Spice India'],
            [234,'IN','Tata Indicom India'],
            [235,'IN','Vodafone India'],
            [236,'IQ','Asia Cell Iraq'],
            [237,'IQ','Korek Iraq'],
            [238,'IQ','Mobitel Iraq'],
            [239,'IQ','Newroz Telecom Iraq'],
            [240,'IQ','Zain Iraq'],
            [241,'IR','MTN Irancell'],
            [242,'IS','Iceland Telecom (Siminn)'],
            [243,'IS','Nova Iceland'],
            [244,'IS','Vodafone Iceland (Og Fjarskipti hf)'],
            [245,'IT','3 Italy'],
            [246,'IT','Tele2 (Vodafone) Italy'],
            [247,'IT','Telecom Italia Mobile'],
            [248,'IT','Vodafone Italy'],
            [249,'IT','Wind Italy'],
            [250,'JM','bMobile Jamaica (Cable & Wireless)'],
            [251,'JM','Digicel Jamaica'],
            [252,'JO','Orange (MobileCOM) Jordan'],
            [253,'JO','Umniah Jordan'],
            [254,'JO','Zain Jordan (Fastlink)'],
            [255,'JP','AU by KDDI Japan'],
            [256,'JP','NTT DoCoMo Japan'],
            [257,'JP','Softbank Mobile Japan'],
            [258,'JP','Willcom Japan'],
            [259,'JP','Yahoo! Japan'],
            [260,'KE','Celtel Kenya'],
            [261,'KE','Econet Wireless Kenya'],
            [262,'KE','Orange Kenya (Telkom Kenya)'],
            [263,'KE','Safaricom Limited Kenya'],
            [264,'KG','BITEL (Sky Mobile) Kyrgyzstan'],
            [265,'KG','MEGACOM (BiMoCom) Kyrgyzstan'],
            [266,'KG','O! (Nurtelecom) Kyrgyzstan'],
            [267,'KH','Cambodia Advance Communications'],
            [268,'KH','CamGSM Cambodia'],
            [269,'KH','Camshin Cambodia'],
            [270,'KH','Star-Cell (Applifone) Cambodia'],
            [271,'KH','TMIC Cambodia'],
            [272,'KH','Viettel Cambodia'],
            [273,'KW','Wataniya Kuwait'],
            [274,'KW','Zain (MTC) Kuwait'],
            [275,'KZ','Beeline (Kar-Tel) Kazakhstan'],
            [276,'KZ','K-Cell Kazakhstan'],
            [277,'KZ','Mobile Telecom Service Kazakhstan'],
            [278,'LA','ETL Mobile Laos'],
            [279,'LA','Lao Telecommunications'],
            [280,'LA','Tigo (Millicom Lao)'],
            [281,'LB','Alfa Lebanon (Cellis)'],
            [282,'LB','MTC Touch Lebanon'],
            [283,'LK','Bharti Airtel Sri Lanka'],
            [284,'LK','Dialog MTN Sri Lanka'],
            [285,'LK','Hutch Sri Lanka'],
            [286,'LK','Mobitel Sri Lanka'],
            [287,'LK','Tigo Celltel Lanka'],
            [288,'LR','Cellcom Liberia'],
            [289,'LR','Libercell (Atlantic Wireless) Liberia'],
            [290,'LR','Lonestar Cell Liberia'],
            [291,'LS','Vodacom Lesotho'],
            [292,'LT','Bite Lithuania'],
            [293,'LT','Omnitel Lithuania'],
            [294,'LT','Tele2 Lithuania'],
            [295,'LU','LuxGSM (P & T, Vodafone) Luxembourg'],
            [296,'LU','Tele2 Luxembourg'],
            [297,'LU','VOXmobile Luxembourg'],
            [298,'LV','LMT Latvia'],
            [299,'LV','Tele2 Latvia'],
            [300,'LY','Al Madar Libya'],
            [301,'LY','Libyan Telecom and Technology'],
            [302,'LY','Libyana Mobile Phone'],
            [303,'MA','Maroc Telecom Morocco'],
            [304,'MA','Meditel Morocco'],
            [305,'MD','Eventis Moldova'],
            [306,'MD','IDC CDMA Interdnestrcom Moldova'],
            [307,'MD','Moldcell Moldova'],
            [308,'MD','Orange Moldova'],
            [309,'ME','m:tel Montenegro'],
            [310,'ME','Promonte Montenegro'],
            [311,'ME','T-Mobile Montenegro'],
            [312,'MG','Orange Madagascar'],
            [313,'MG','Telma Mobile Madagascar'],
            [314,'MK','COSMOFON Macedonia'],
            [315,'MK','T-Mobile Macedonia'],
            [316,'MK','VIP Operator Macedonia'],
            [317,'ML','Orange (Ikatel) Mali'],
            [318,'ML','SOTELMA Mali'],
            [319,'MN','G-Mobile Mongolia'],
            [320,'MN','MobiCom Mongolia'],
            [321,'MN','Unitel Mongolia'],
            [322,'MO','CTM Macao'],
            [323,'MP','PTI Pacifica Northern Mariana Islands'],
            [324,'MR','MATTEL Mauritania'],
            [325,'MT','Go Mobile Malta'],
            [326,'MT','Melita Mobile (3 G Telecoms) Malta'],
            [327,'MT','Vodafone Malta'],
            [328,'MU','Emtel Mauritius'],
            [329,'MU','Orange (Cellplus) Mauritius'],
            [330,'MV','Touch (Dhiraagu) Maldives'],
            [331,'MV','Wataniya Maldives'],
            [332,'MW','Zain Malawi'],
            [333,'MX','Iusacell Mexico'],
            [334,'MX','Telcel (AmÃ©rica MÃ³vil) Mexico'],
            [335,'MX','Telefonica Mexico'],
            [336,'MY','Celcom Malaysia'],
            [337,'MY','Digi Malaysia'],
            [338,'MY','Maxis Malaysia'],
            [339,'MY','U Mobile (Mi3G/MiTV) Malaysia'],
            [340,'MZ','mCel Mozambique'],
            [341,'MZ','Vodacom Mozambique'],
            [342,'NA','MTC Namibia'],
            [343,'NA','Powercom (Cell One) Namibia'],
            [344,'NC','(MOBILIS) OPT New Caledonia'],
            [345,'NE','Moov Niger'],
            [346,'NE','Orange Niger'],
            [347,'NG','Celtel/Zain Nigeria'],
            [348,'NG','EMTS (Mubadala, Etisalat) Nigeria'],
            [349,'NG','Glo Mobile (Globacom)'],
            [350,'NG','MTN Nigeria'],
            [351,'NG','Reltel Nigeria'],
            [352,'NI','Claro (Enitel) Nicaragua'],
            [353,'NL','KPN (Telfort) Netherlands'],
            [354,'NL','T-Mobile Netherlands'],
            [355,'NL','Tele2 Netherlands'],
            [356,'NL','Vodafone Netherlands'],
            [357,'NO','Mobile Norway'],
            [358,'NO','Netcom Norway'],
            [359,'NO','TDC Mobil Norway'],
            [360,'NO','Tele2 Norway'],
            [361,'NO','Telenor Norway'],
            [362,'NO','Ventelo Norway'],
            [363,'NP','Mero Mobile Nepal'],
            [364,'NP','Nepal Telecom Mobile'],
            [365,'NZ','Telecom New Zealand'],
            [366,'NZ','Vodafone New Zealand'],
            [367,'OM','Nawras Oman'],
            [368,'OM','Oman Mobile'],
            [369,'PA','Digicel Panama'],
            [370,'PA','MÃ³vil (Cable & Wireless) Panama'],
            [371,'PA','Telefonica Panama'],
            [372,'PE','America Movil (Claro) Peru'],
            [373,'PE','Claro Peru'],
            [374,'PE','Telefonica Movistar Peru'],
            [375,'PF','VINI (Tikiphone) French Polynesia'],
            [376,'PG','Digicel Papua New Guinea'],
            [377,'PH','Globe Telecom Philippines'],
            [378,'PH','Smart Communications Philippines'],
            [379,'PH','Sun Cellular (Digitel) Philippines'],
            [380,'PK','Mobilink Pakistan'],
            [381,'PK','Pakistan Telecommunciation Mobile (Ufone)'],
            [382,'PK','Telenor Pakistan'],
            [383,'PK','Warid Pakistan'],
            [384,'PK','Wateen Pakistan'],
            [385,'PK','ZONG Pakistan (CMPAK)'],
            [386,'PL','Era Poland'],
            [387,'PL','Play Poland (P4 Sp. z o.o)'],
            [388,'PL','Plus GSM Poland'],
            [389,'PL','PTK Centertel (Orange) Poland'],
            [390,'PR','Centennial de Puerto Rico'],
            [391,'PR','Open Mobile Puerto Rico'],
            [392,'PR','Verizon Wireless Puerto Rico'],
            [393,'PS','Jawwal (Paltel) Palestine'],
            [394,'PT','Optimus Portugal'],
            [395,'PT','TMN Portugal'],
            [396,'PT','Vodafone Portugal'],
            [397,'PY','Nucleo Personal PARAGUAY'],
            [398,'PY','Telecel Paraguay'],
            [399,'PY','VOX (Hola Paraguay)'],
            [400,'QA','Qtel Mobile Qatar'],
            [401,'RE','Only (Outremer) Reunion'],
            [402,'RE','Orange RÃ©union'],
            [403,'RO','Cosmote Romania'],
            [404,'RO','Orange Romania'],
            [405,'RO','Vodafone (Mobifon) Romania'],
            [406,'RS','IPKO Kosovo'],
            [407,'RS','Telekom Srbija'],
            [408,'RS','Telenor (Mobtel) Serbia'],
            [409,'RS','Vala (PTK) Kosovo'],
            [410,'RS','VIP Mobile Serbia'],
            [411,'RU','Aquafon Russia'],
            [412,'RU','Bashcell Russia'],
            [413,'RU','Baykalwestcom Russia'],
            [414,'RU','Beeline Russia'],
            [415,'RU','BM-Telecom (Bashkiria-Mobel Telecom) Russia (Ufa)'],
            [416,'RU','CenterTelecom Russia'],
            [417,'RU','Far East Cellular Systems Russia'],
            [418,'RU','JSC CTeK Russia (Cellular Telephone of Kuzbass GSM)'],
            [419,'RU','JSC Saratov-Mobile Russia'],
            [420,'RU','Megafon Russia'],
            [421,'RU','Mobile TeleSystems Russia'],
            [422,'RU','MOTIV (LLC Ekaterinburg-2000) Russia'],
            [423,'RU','Multiregional Transit Telecom Russia'],
            [424,'RU','New Telephone Company Russia'],
            [425,'RU','Nizhegorodskaya Cellular Communications Russia'],
            [426,'RU','ON GSM Saratov'],
            [427,'RU','Orenburg-GSM Russia'],
            [428,'RU','Sakhalin GSM Russia'],
            [429,'RU','Sibirtelecom Russia'],
            [430,'RU','SkyLink Russia'],
            [431,'RU','SMARTS Russia'],
            [432,'RU','STEK GSM Russia'],
            [433,'RU','TAIF Telcom Russia'],
            [434,'RU','Tatincom-T Russia'],
            [435,'RU','Tele2 Russia'],
            [436,'RU','TransTeleKom Russia'],
            [437,'RU','Ulyanovsk-GSM Russia'],
            [438,'RU','USI (Uralsvyazinform) Russia'],
            [439,'RU','VolgaTelecom Russia'],
            [440,'RU','Volgograd-GSM Russia'],
            [441,'RW','MTN Rwandacell'],
            [442,'RW','Rwandatel'],
            [443,'SA','Al Jawal (Saudi Telecom Company) Saudi Arabia'],
            [444,'SA','Ettihad Etisalat (Mobily) Saudi Arabia'],
            [445,'SA','Zain (MTC) Saudi Arabia'],
            [446,'SC','Cable & Wireless (Atlas) Seychelles'],
            [447,'SD','Canar Telecom Sudan'],
            [448,'SD','MTN (Areeba) Sudan'],
            [449,'SD','Sudan Telecom (Sudani)'],
            [450,'SD','Zain (Mobitel) Sudan'],
            [451,'SE','3 Sweden'],
            [452,'SE','Spring Mobil Sweden'],
            [453,'SE','Tele2 Sweden'],
            [454,'SE','Telia Sweden'],
            [455,'SE','Vodafone (Telenor) Sweden'],
            [456,'SG','M1 Singapore'],
            [457,'SG','SingTel Mobile Singapore'],
            [458,'SG','Starhub Singapore'],
            [459,'SI','Mobitel Slovenia'],
            [460,'SI','Si.mobil Slovenia'],
            [461,'SI','T-2 d.o.o. Slovenia'],
            [462,'SI','TuÂšmobil Slovenia'],
            [463,'SK','Orange Slovakia'],
            [464,'SK','T-Mobile Slovakia'],
            [465,'SK','TelefÃ³nica O2 Slovakia'],
            [466,'SL','Comium Sierra Leone'],
            [467,'SL','Tigo (Millicom) Sierra Leone'],
            [468,'SM','San Marino Telecom'],
            [469,'SN','Sonatel Senegal (Orange)'],
            [470,'SO','Somafone Somalia'],
            [471,'SO','Stel Communications Somalia'],
            [472,'SR','TELESUR.GSM Suriname'],
            [473,'SR','Uniqa Suriname & UTS Netherlands Antilles'],
            [474,'SV','Digicel El Salvador'],
            [475,'SV','Telefonica Movistar El Salvador'],
            [476,'SV','Telemovil El Salvador'],
            [477,'SY','Mobile Syria (Syrian Telecommunication Est.)'],
            [478,'SY','MTN Syria'],
            [479,'SY','Syriatel Mobile Telecom'],
            [480,'SZ','Swazi MTN Swaziland'],
            [481,'TD','Millicom Chad'],
            [482,'TG','Togo Cell'],
            [483,'TH','AIS Thailand'],
            [484,'TH','DTAC Thailand'],
            [485,'TH','Hutchison CAT Thailand'],
            [486,'TH','True Move Thailand'],
            [487,'TJ','Babilon-Mobile Tajikistan'],
            [488,'TJ','Beeline (Tacom) Tajikistan'],
            [489,'TN','TUNISIANA (Orascom) Tunisia'],
            [490,'TN','Tuntel Tunisia'],
            [491,'TR','Avea Turkey'],
            [492,'TR','KUZEY KIBRIS TURKCELL Turkey'],
            [493,'TR','Turkcell Turkey'],
            [494,'TR','Vodafone (Telsim) Turkey'],
            [495,'TT','Digicel Trinidad and Tobago'],
            [496,'TT','TSTT (bMobile) Trinidad and Tobago'],
            [497,'TW','CHT Emome Taiwan'],
            [498,'TW','Far EasTone Taiwan'],
            [499,'TW','Taiwan Mobile'],
            [500,'TW','VIBO Taiwan'],
            [501,'TZ','Celtel Tanzania'],
            [502,'TZ','Tigo Tanzania'],
            [503,'TZ','Vodacom Tanzania'],
            [504,'TZ','Zantel Tanzania'],
            [505,'UA','Beeline (Ukrainian Radio Systems)'],
            [506,'UA','CDMA Ukraine (ITC)'],
            [507,'UA','Kyivstar Ukraine'],
            [508,'UA','Life Ukraine'],
            [509,'UA','Ukrainian Mobile Communications (MTS)'],
            [510,'UA','Utel Ukraine'],
            [511,'UG','Celtel (Zain) Uganda'],
            [512,'UG','MTN Uganda'],
            [513,'UG','Orange Uganda'],
            [514,'UG','UT Mobile Uganda'],
            [515,'UG','WARID Telecom Uganda'],
            [516,'US','Alaska Communications Systems'],
            [517,'US','Alltel USA'],
            [518,'US','Amazon Web Services'],
            [519,'US','Appalachian Wireless USA'],
            [520,'US','AT&T Mobility USA'],
            [521,'US','Bluegrass Cellular USA'],
            [522,'US','Boost USA'],
            [523,'US','Cellcom USA'],
            [524,'US','Cellular One USA'],
            [525,'US','Cellular South USA'],
            [526,'US','Centennial Wireless (Michiana Metronet) USA'],
            [527,'US','Cincinnati Bell'],
            [528,'US','ClearSky Mobile Media USA (Hosted WAP Gateways)'],
            [529,'US','Commnet Wireless USA'],
            [530,'US','Corr Wireless USA'],
            [531,'US','Cricket Wireless USA'],
            [532,'US','CSDCO USA (Hosted WAP Gateways)'],
            [533,'US','Danger'],
            [534,'US','Dobson USA'],
            [535,'US','Edge Wireless USA'],
            [536,'US','Einstein Wireless (Airadigm) USA'],
            [537,'US','Five Star Wireless'],
            [538,'US','GoAmerica USA'],
            [539,'US','Golden State Cellular'],
            [540,'US','Hargray USA'],
            [541,'US','Helio USA'],
            [542,'US','Inland Cellular USA'],
            [543,'US','Interop Technologies USA (Hosted WAP Gateways)'],
            [544,'US','Kindle Gateway (Qualcomm) USA'],
            [545,'US','Leaco Rural Wireless USA'],
            [546,'US','Long Lines Wireless USA'],
            [547,'US','Metro PCS USA'],
            [548,'US','Mobi PCS USA'],
            [549,'US','NEX-TECH USA'],
            [550,'US','Nextel USA'],
            [551,'US','North Valley Communications South Dakota USA'],
            [552,'US','Openwave Systems USA (Hosted WAP Gateways)'],
            [553,'US','Pine Cellular USA'],
            [554,'US','Pioneer Cellular USA'],
            [555,'US','Plateautel Wireless USA'],
            [556,'US','Pocket Communications USA'],
            [557,'US','Research In Motion USA'],
            [558,'US','Revol Wireless USA'],
            [559,'US','Simmetry (Adams) USA'],
            [560,'US','SouthernLINC USA'],
            [561,'US','Sprint PCS USA'],
            [562,'US','SRT Communications USA'],
            [563,'US','Star Search Rural Cellular (Oklahoma Western Telephone) USA'],
            [564,'US','Suncom Wireless USA (Triton PCS)'],
            [565,'US','T-Mobile USA'],
            [566,'US','Thumb Cellular (Agri Valley Communications) USA'],
            [567,'US','U.S. Cellular USA'],
            [568,'US','UBET Wireless USA'],
            [569,'US','UNICEL (Rural Cellular) USA'],
            [570,'US','Union Telephone Company'],
            [571,'US','Verizon Wireless USA'],
            [572,'US','Viaero USA'],
            [573,'US','Virgin Mobile USA'],
            [574,'US','West Central Wireless USA'],
            [575,'US','Westlink Communications USA'],
            [576,'US','Wireless Data Service Provider Corporation'],
            [577,'UY','Ancel Uruguay'],
            [578,'UY','Telefonica Moviles Uruguay'],
            [579,'UZ','Beeline (Unitel) Uzbekistan'],
            [580,'UZ','Ucell (Coscom) Uzbekistan'],
            [581,'UZ','Uzdunrobita GSM Uzbekistan'],
            [582,'VE','Digitel Venezuela'],
            [583,'VE','movilnet Venezuela'],
            [584,'VE','Movistar (Telcel) Venezuela'],
            [585,'VG','Cable & Wireless British Virgin Islands'],
            [586,'VN','EVN Telecom Mobile Vietnam'],
            [587,'VN','Mobifone (VMS) Vietnam'],
            [588,'VN','S-Fone Vietnam'],
            [589,'VN','Vietel'],
            [590,'VN','Vietnamobile (Hanoi Telecom)'],
            [591,'VN','Vinaphone Vietnam'],
            [592,'WS','Digicel Samoa'],
            [593,'WS','GoMobile SamoaTel'],
            [594,'YE','MTN Spacetel Yemen'],
            [595,'YE','Sabafon (Yemen Mobile Phone Company)'],
            [596,'YE','Y (HiTS-UNITEL) Yemen'],
            [597,'ZA','Cell C South Africa'],
            [598,'ZA','MTN South Africa'],
            [599,'ZA','Nashua Mobile'],
            [600,'ZA','Telkom'],
            [601,'ZA','Vodacom South Africa'],
            [602,'ZM','Celtel Zambia'],
            [603,'ZM','MTN Zambia'],
            [604,'ZW','Econet Zimbabwe'],
        ]);

        $this->batchInsert('{{%mts_devicetype}}',['id','name'],[
            [1,'Desktop'],
            [2,'Mobile'],
            [3,'Tablet'],
            [4,'Robot'],
        ]);

        $this->batchInsert('{{%mts_model}}',['id','name','brandID'],[
            [1,'BlackBerry 7290','1'],
            [2,'G1','2'],
            [3,'PC','3'],
            [4,'iPhone','4'],
            [5,'Nexus 7','5'],
            [6,'GT-S5360','6'],
            [7,'GT-S5301','6'],
            [8,'N73','7'],
            [9,'GT-I9070','6'],
            [10,'GT-I9100','6'],
            [11,'E5-00','7'],
            [12,'E63','7'],
            [13,'C7-00','7'],
            [14,'C5-00','7'],
            [15,'C5-03','7'],
            [16,'GT-I9500','6'],
            [17,'6700 slide','7'],
            [18,'MT11i','8'],
            [19,'GT-S6810P','6'],
            [20,'E72','7'],
            [21,'GT-I9082','6'],
            [22,'GT-I9003','6'],
            [23,'GT-S5312','6'],
            [24,'GT-S7582','6'],
            [25,'GT-I9300','6'],
            [26,'GT-S5830i','6'],
            [27,'GT-S7562','6'],
            [28,'GT-I8262','6'],
            [29,'E71','7'],
            [30,'6680','7'],
            [31,'GT-S5830','6'],
            [32,'GT-S5280','6'],
            [33,'E66','7'],
            [34,'Iconia B1-710','9'],
            [35,'GT-S6312','6'],
            [36,'Android 4.2','10'],
            [37,'GT-I8190','6'],
            [38,'N320','11'],
            [39,'GT-I8150','6'],
            [40,'GT-I9105P','6'],
            [41,'SM-N9005','6'],
            [42,'Android 4.4','10'],
            [43,'GT-P3100','6'],
            [44,'Y300','12'],
            [45,'C6-00','7'],
            [46,'E445','13'],
            [47,'GT-B5512','6'],
            [48,'GT-S6102','6'],
            [49,'GT-S6802','6'],
            [50,'5800 XpressMusic','7'],
            [51,'Android 4.3','10'],
            [52,'E6-00','7'],
            [53,'GT-S6810','6'],
            [54,'SM-N900','6'],
            [55,'C6603','8'],
            [56,'Robot','14'],
            [57,'GT-I9190','6'],
            [58,'GT-I9295','6'],
            [59,'Android 4.1 Tablet','10'],
            [60,'A310e','15'],
            [61,'LT25i','16'],
            [62,'Robot','17'],
            [63,'T328w','15'],
            [64,'GT-I9195','6'],
            [65,'A116','18'],
            [66,'GT-S7390','6'],
            [67,'Android 4.0','10'],
            [68,'GT-I9105','6'],
            [69,'GT-I8552','6'],
            [70,'E51','7'],
            [71,'6710','7'],
            [72,'E52','7'],
            [73,'GT-S7270','6'],
            [74,'SM-T211','6'],
            [75,'Android 4.1','10'],
            [76,'Android 2.3','10'],
            [77,'GT-P6200','6'],
            [78,'N86 8MP','7'],
            [79,'701','7'],
            [80,'5233','7'],
            [81,'GT-S5570','6'],
            [82,'LT18a','8'],
            [83,'ST21i2','16'],
            [84,'GT-S5282','6'],
            [85,'A2107A-H','19'],
            [86,'P705','13'],
            [87,'GT-N7100','6'],
            [88,'LT18i','8'],
            [89,'N8-00','7'],
            [90,'GT-S5302','6'],
            [91,'Lenovo A516','19'],
            [92,'Android 4 Tablet','10'],
            [93,'GT-I5503','6'],
            [94,'A6','20'],
            [95,'One mini','15'],
            [96,'GT-I9505','6'],
            [97,'GT-S5660','6'],
            [98,'ST18i','8'],
            [99,'Desire 500','15'],
            [100,'C1904','16'],
            [101,'Milestone','21'],
            [102,'GT-N8000','6'],
            [103,'N95','7'],
            [104,'C5-06','7'],
            [105,'500','7'],
            [106,'E75','7'],
            [107,'N82','7'],
            [108,'SHV-E160S','6'],
            [109,'5630','7'],
            [110,'5530','7'],
            [111,'GT-S6012','6'],
            [112,'603','7'],
            [113,'ST23i','16'],
            [114,'700','7'],
            [115,'6120 classic','7'],
            [116,'GT-S5570I','6'],
            [117,'GT-I9305','6'],
            [118,'GT-I9152','6'],
            [119,'ST26i','16'],
            [120,'E7-00','7'],
            [121,'GT-I9200','6'],
            [122,'C2105','16'],
            [123,'Wildfire','15'],
            [124,'A8181','15'],
            [125,'OT-4007D','22'],
            [126,'N95 8GB','7'],
            [127,'G700-U10','12'],
            [128,'GT-S7262','6'],
            [129,'A810e','15'],
            [130,'SM-T210','6'],
            [131,'GT-I8190N','6'],
            [132,'A1','23'],
            [133,'A62','18'],
            [134,'C6-01','7'],
            [135,'SensationXE Beats Z715e','15'],
            [136,'GT-S7580','6'],
            [137,'A10','24'],
            [138,'5230','7'],
            [139,'X6-00','7'],
            [140,'E410','13'],
            [141,'WT19i','8'],
            [142,'GT-S7272','6'],
            [143,'GT-S6812','6'],
            [144,'GT-I5800','6'],
            [145,'Android 4.2 Tablet','10'],
            [146,'GT-B5330','6'],
            [147,'GT-P5100','6'],
            [148,'GT-S5300','6'],
            [149,'GT-S7500L','6'],
            [150,'E615','13'],
            [151,'A35','18'],
            [152,'GT-I9070P','6'],
            [153,'Android 4.1','25'],
            [154,'PC','26'],
            [155,'N72','7'],
            [156,'Robot','27'],
            [157,'One V','15'],
            [158,'T9292','15'],
            [159,'Robot','28'],
            [160,'GT-P6200L','6'],
            [161,'E400','13'],
            [162,'GT-S5830T','6'],
            [163,'GT-S5360T','6'],
            [164,'SGH-T999','6'],
            [165,'P999','13'],
            [166,'Firefox for Android','29'],
            [167,'P3','30'],
            [168,'Y210-0100','12'],
            [169,'PJ83100','15'],
            [170,'U8680','2'],
            [171,'LT26i','8'],
            [172,'A10','31'],
            [173,'GT-S5303','6'],
            [174,'Desire HD','15'],
            [175,'SK17i','8'],
            [176,'GT-S6500','6'],
            [177,'GT-P1000','6'],
            [178,'U8800 Pro','12'],
            [179,'P350','13'],
            [180,'LT15i','8'],
            [181,'A9191','15'],
            [182,'P930','13'],
            [183,'GT-S5360B','6'],
            [184,'GT-N7000','6'],
            [185,'U8665','12'],
            [186,'SGH-T989','6'],
            [187,'SGH-I897','6'],
            [188,'P500','13'],
            [189,'U8500','12'],
            [190,'GT-I9000','6'],
            [191,'U8800-51','12'],
            [192,'BM-SWU300','12'],
            [193,'N3','30'],
            [194,'GT-I8552B','6'],
            [202,'XT862','21'],
            [203,'GT540','13'],
            [204,'GT-P3110','6'],
            [205,'P505','13'],
            [206,'GT-I8160L','6'],
            [207,'S7_Slim','12'],
            [208,'Dream','15'],
            [209,'U8650','12'],
            [210,'myTouch 4G Slide','15'],
            [211,'SM-C101','6'],
            [212,'975N','32'],
            [213,'1000C','15'],
            [214,'U8150','12'],
            [215,'ZTE LEO Q1','33'],
            [216,'P509','13'],
            [217,'GT-S7270L','6'],
            [218,'MediaPad 7 Lite','12'],
            [219,'Inspire 4G','15'],
            [220,'GT-S5310','6'],
            [221,'GT-S5670','6'],
            [222,'U8185','12'],
            [223,'PJ83100','25'],
            [224,'GT-N8010','6'],
            [225,'GT-S7560','6'],
            [226,'SM-T111','6'],
            [228,'OT-4033D','22'],
            [229,'GT-S7500','6'],
            [230,'OT-5036D','22'],
            [231,'GT-N5100','6'],
            [232,'Android 2.0','10'],
            [234,'Robot','34'],
            [235,'LT22i','8'],
            [236,'GT-S5310B','6'],
            [237,'GT-I8160','6'],
            [238,'Tablet S','16'],
            [239,'E90 Communicator','7'],
            [240,'GT-P6800','6'],
            [242,'Flyer','15'],
            [243,'MID7010','35'],
            [244,'P768','13'],
            [245,'S1','36'],
            [246,'SM-T311','6'],
            [249,'S510e','15'],
            [250,'GT-P7500','6'],
            [251,'SM-G900F','6'],
            [252,'IQ 5','37'],
            [253,'Firefox for Android Tablet','29'],
            [256,'GT-S5300B','6'],
            [258,'GT-P5200','6'],
            [259,'ST25a','8'],
            [260,'Y210-0151','12'],
            [261,'C1505','16'],
            [262,'GT-N7102','6'],
            [264,'GT-P1000T','6'],
            [265,'J2ME Midlet','10'],
            [266,'GT-S5570B','6'],
            [268,'GT-I5510','6'],
            [269,'X909','38'],
            [270,'GT-I9100T','6'],
            [271,'Android 3.2','10'],
            [272,'GT-I9082L','6'],
            [273,'ST27i','8'],
            [274,'Nexus 4','5'],
            [277,'P970','13'],
            [279,'GT-S6310','6'],
            [281,'C1905','16'],
            [282,'XT910','21'],
            [283,'SHV-E160L','6'],
            [285,'C1605','16'],
            [287,'G510-0010','12'],
            [288,'A2','24'],
            [289,'A3000-H','19'],
            [290,'GT-P1010','6'],
            [291,'GT-S7562L','6'],
            [292,'MB525','21'],
            [293,'MB860','21'],
            [294,'GT-S6810L','6'],
            [295,'S710E','15'],
            [297,'ST21i','16'],
            [298,'Android App Engine','5'],
            [299,'GT-I9100P','6'],
            [300,'A8','24'],
            [301,'P715','13'],
            [302,'U9200','12'],
            [303,'G525-U00','12'],
            [304,'GT-I9300','39'],
            [305,'C2305','16'],
            [306,'D802','13'],
            [307,'MT25i','8'],
            [310,'ST25i','8'],
            [311,'GT-S5369','6'],
            [313,'S650','19'],
            [314,'ST17i','8'],
            [315,'M7','15'],
            [316,'F307','40'],
            [317,'GT-S5363','6'],
            [318,'Android 4.3 Tablet','10'],
            [319,'JY-G3','41'],
            [320,'Android 3.1','10'],
            [321,'E15i','8'],
            [322,'U9508','12'],
            [323,'PAP3540DUO','42'],
            [324,'Android 2.2','10'],
            [325,'A7+','43'],
            [326,'C5502','16'],
            [329,'GT-N5110','6'],
            [330,'B1-A71','9'],
            [332,'P880','13'],
            [333,'P990','13'],
            [335,'GT-I9001','6'],
            [336,'A510e','15'],
            [337,'X5292','44'],
            [339,'A4+','43'],
        ]);
        $this->batchInsert('{{%mts_isp}}',['id','name','countryCode'],[
            [2,'China Telecom SHANGHAI','CN'],
            [3,'1-Net Singapore','SG'],
            [4,'SFR','FR'],
            [5,'Emirates Integrated Telecommunications Company PJS','AE'],
            [6,'Dubai Marina Mall Hotel','AE'],
            [7,'IC-POP','AE'],
            [8,'Shaheen Zulfikar Ali Bhutto Institute of Science &','AE'],
            [9,'JI POP','AE'],
            [10,'Google','US'],
            [11,'Blue Coat Systems','US'],
            [12,'Dubai Sports City','AE'],
            [13,'Opera Mini Proxy','EU'],
            [14,'Radisson SAS Hotel','AE'],
            [15,'Mirdif POP','AE'],
            [16,'Chinatelecom Next Carrying HongKong region network','HK'],
            [17,'True Internet','TH'],
            [18,'Korea Telecom','KR'],
            [19,'China Telecom Hangzhou','CN'],
            [20,'Advance Wireless Network','TH'],
            [21,'Total Access Communication PLC','TH'],
            [22,'3BB Broadband','TH'],
            [23,'True Hi-Speed (Broadband)','TH'],
            [24,'453 Ladplacout Jorakhaebua','TH'],
            [25,'TM Net','MY'],
            [26,'Ghana Telecom','GH'],
            [27,'Scancom Ltd','EG'],
            [28,'zain-as','GH'],
            [29,'Millicom Ghana Limited','GH'],
            [30,'Safaricom-limited','KE'],
            [31,'AIS Mobile','TH'],
            [32,'Realmove Company Limited','TH'],
            [33,'Vodafone Ghana','GH'],
            [34,'Alcatel Project','GH'],
            [35,'Dedicated Internet Customers','GH'],
            [36,'Super Broadband Network','TH'],
            [37,'True Move Company Limited','TH'],
            [38,'Equipment is Huawei','TH'],
            [39,'True Broadband by True Online','TH'],
            [40,'SBN-ISP and SBN-NIX','TH'],
            [41,'Truemove','TH'],
            [42,'Equipment is Shasta','TH'],
            [43,'Dtac Broadband Co.,ltd.','TH'],
            [44,'Wangsu Science And Technology (us)','US'],
            [45,'PTTICT Solutions Co.,Ltd.','TH'],
            [46,'Mahanagar Telephone Nigam Ltd.','IN'],
            [47,'The American University in Dubai','AE'],
        ]);

        $this->batchInsert('{{%mts_os}}',['id','name'],[
            [1,'Android'],
            [2,'FreeBSD'],
            [3,'OpenBSD'],
            [4,'Linux'],
            [5,'MacOSX'],
            [6,'SunOS'],
            [7,'Windows'],
            [8,'ChromeOS'],
            [9,'Symbian OS'],
            [10,'Linux Smartphone OS'],
            [11,'Windows Mobile OS'],
            [12,'Rex Qualcomm OS'],
            [13,'iOS'],
            [14,'Windows Phone OS'],
            [15,'MeeGo'],
            [16,'Bada OS'],
            [17,'RIM OS'],
            [18,'MTK/Nucleus OS'],
            [19,'Palm OS'],
            [20,'webOS'],
            [21,'Windows RT'],
            [22,'Desktop'],
            [23,'Windows CE'],
            [24,'Hiptop OS'],
            [25,'RIM Tablet OS'],
            [26,'Firefox OS'],
            [27,'unknown'],
            [28,'Debian'],
            [29,'Macintosh']
        ]);

        $this->batchInsert('{{%mts_resolution}}',['id','name'],[
            [1,'240x160'],
            [2,'320x480'],
            [3,'1024x768'],
            [4,'800x1280'],
            [5,'240x320'],
            [6,'480x800'],
            [7,'320x240'],
            [8,'360x640'],
            [9,'1080x1920'],
            [10,'480x854'],
            [11,'720x1280'],
            [12,'176x208'],
            [13,'600x1024'],
            [14,'640x480'],
            [15,'540x960'],
            [16,'800x600'],
            [17,'640x360'],
            [18,'1920x1080'],
            [19,'1280x800'],
            [20,'480x320'],
            [21,'240x400'],
            [22,'800x480'],
            [23,'800x352'],
            [24,'176x120'],
            [25,'1280x768'],
            [26,'768x1280']
        ]);

        $this->batchInsert('{{%mts_size}}',['id','name'],[
            [1,'27x27'],
            [2,'45x68'],
            [3,'1024x768'],
            [4,'50x74'],
            [5,'95x151'],
            [6,'46x61'],
            [7,'43x57'],
            [8,'37x49'],
            [9,'53x88'],
            [10,'57x94'],
            [11,'48x36'],
            [12,'44x78'],
            [13,'34x45'],
            [14,'40x71'],
            [15,'63x111'],
            [16,'34x50'],
            [17,'66x109'],
            [18,'60x107'],
            [19,'34x41'],
            [20,'90x154'],
            [21,'47x70'],
            [22,'49x66'],
            [23,'49x81'],
            [24,'71x127'],
            [25,'54x81'],
            [26,'53x40'],
            [27,'48x64'],
            [28,'50x38'],
            [29,'54x96'],
            [30,'92x153'],
            [31,'82x122'],
            [32,'400x400'],
            [33,'62x103'],
            [34,'30x41'],
            [35,'40x53'],
            [36,'78x44'],
            [37,'46x68'],
            [38,'69x122'],
            [39,'57x100'],
            [40,'709x399'],
            [41,'50x89'],
            [42,'218x136'],
            [43,'41x72'],
            [44,'72x115'],
            [45,'37x65'],
            [46,'73x129'],
            [47,'79x140'],
            [48,'55x37'],
            [49,'56x84'],
            [50,'42x70'],
            [51,'52x78'],
            [52,'57x85'],
            [53,'50x84'],
            [54,'50x66'],
            [55,'59x105'],
            [56,'40x60'],
            [57,'43x64'],
            [58,'53x93'],
            [59,'53x95'],
            [60,'60x99'],
            [61,'50x83'],
            [62,'153x92'],
            [63,'20x60'],
            [64,'108x173'],
            [65,'217x136'],
            [66,'61x30'],
            [67,'104x166'],
            [68,'136x218'],
            [69,'47x82'],
            [70,'65x116'],
            [71,'46x77'],
            [72,'192x120'],
            [73,'58x102']
        ]);

        $this->batchInsert('{{%mts_trafficsource}}',['id','name','costType','c1','c2','c3','c4','c5','c6','c7','c8','c9','c10'],
            [
                [ 1,'Buzzcity', '1', '{placement}', '{creative}', '', '', '', '', '', '', '', ''],
                [ 2,'Airpush', '1',  '{placement}', '{creative}', '%d%', '%version%', '%pubid%', '%guid%', '%dapp%', '%manufacturer%', '%androidid%', '%carrier%'],
                [ 3,'Leadbolt', '1',  '{placement}', '{creative}', '[CAT_ID]', '[PLATFORM]', '[MAC]', '[DEVICE_ID]', '[CAMP_ID]', '[AD_ID]', '', ''],
                [ 4,'MMedia', '1',  '{placement}', '{creative}', '[:_jv_apid:]', '', '', '', '', '', '', ''],
                [ 5,'Mobfox', '1', '{placement}', '{creative}', 'MFOXPUBID', 'MFOXUDID', 'MFOXIFA', '', '', '', '', ''],
                [ 6,'SiteScout Rtb', '2', '{placement}', '{creative}', '{adId}', '{siteId}', '{campaignId} ', '{networkId}', '{postbackId}', '{domain}', '{carrier}', '{device}'],
                [ 7,'Adwords Display', '1',  '{placement}', '{creative}', '{target}', '{network}', '{ifmobile:Y}', '{ifcontent:Y}', '', '', '', ''],
                [ 8,'Ad On Network', '2',  '{placement}', '{creative}', 'SEARCHTEXT', 'PARTNERID', '${referurl}$', '', '', '', '', ''],
                [ 9,'Adoori', '2',  '{placement}', '{creative}', 'keywordSearched', '', '', '', '', '', '', ''],
                [ 10,'Bing', '1',  '{placement}', '{creative}', '{keyword}', '{QueryString}', '{MatchType}', '', '', '', '', ''],
                [ 11,'ExoClick', '1','{placement}', '{creative}', '{src_hostname}', '{campaign_id}', '{keyword}', '', '', '', '', ''],
                [ 12,'Adwords Search', '1', '{placement}', '{creative}', '{keyword}', '{matchtype}', '{adposition}', '{network}', '{ifmobile:Y}', '{ifsearch:Y}', '{ifcontent:Y}', ''],
                [ 13,'JumpTap', '1', '{placement}', '{creative}', 'JT_KEYWORD', 'JT_ADBUNDLE', 'JT_PUBLISHER', 'JT_SITE', 'JT_HANDSET', 'JT_OPERATOR', '', ''],
                [ 14,'Lead Impact', '2',  '{placement}', '{creative}', '%KEYWORD%', '', '', '', '', '', '', ''],
                [ 15,'Plenty of Fish', '1',  '{placement}', '{creative}', '{creativeid:}', '{state:default}', '{gender:default}', '{age:default}', '', '', '', ''],
                [ 16,'adultmoda', '1',  '{placement} ', '{creative} ', '%zoneid%', '%adid%', '%campaignid%', '%clickid%', '%cpc%', '%cpc-usd%', '', ''],
                [ 17,'Facebook', '1',  '{placement}', '{creative}', '', '', '', '', '', '', '', ''],
                [ 18,'admoda', '1',  '{placement}', '{creative}', '%campaignid%', '%zoneid%', '%adid%', '%clickid%', '%cpc%', '%cpc-usd%', '', ''],
                [ 19,'mobadge', '1', '{placement} ', '{creative} ', '', '', '', '', '', '', '', '']
            ]);



        $this->batchInsert('{{%mts_network}}',['id','name','systemType'],[
            [1,'Yeahmobi','Custom'],
            [2,'Avazu','Custom'],
            [3,'Mobvista','Hasoffers'],
            [4,'Moboglobal','Hasoffers'],
        ]);

        $this->batchInsert('{{%mts_cloak}}',['id','type','name','rule'],[
            [1,1,'Adcenter IPs',"68.142.192.0-68.142.255.255
8.12.144.0-8.12.144.255
157.54.0.0-157.60.255.255
195.128.18.0-195.128.18.255
202.160.176.0-202.160.191.255
207.46.0.0-207.46.255.255
207.68.128.0-207.68.207.255
209.131.32.0-209.131.63.255
209.191.64.0-209.191.127.255
216.145.48.0-216.145.63.255
216.252.96.0-216.252.127.255
64.4.0.0-64.4.63.255
65.52.0.0-65.55.255.255
66.196.64.0-66.196.127.255
66.228.160.0-66.228.191.255
67.195.0.0-67.195.255.255
72.30.0.0-72.30.255.255
74.6.0.0-74.6.255.255"],
            [2,3,'Adcenter UA',"yahoo!
bingbot
slurp
msnbot
adidxbot
yahooseeker"],
            [3,3,'AiHit',"aiHitBot"],
            [4,2,'Amazon.com',"204.236.226.210"],
            [5,2,'AOL',"64.12.116.80"],
            [6,2,'APNIC',"123.125.71.43
150.70.172.206"],
            [7,1,'APNIC IPs',"150.1.0.0-150.101.255.255
115.0.0.0-115.255.255.255
113.0.0.0-113.255.255.255
114.0.0.0-114.255.255.255
61.0.0.0-61.255.255.255
111.13.8.0-111.13.8.100"],
            [8,1,"Baidu","180.76.5.0-180.76.6.255"],
            [9,1,"Bluecoat","199.19.248.0-199.19.255.255"],
            [10,3,"Catch All UAs","crawl
crawler"],
            [11,1,"Facebook","192.41.0.0-192.41.101.255
76.72.165.0-76.72.165.127
66.93.78.176-66.93.78.183
65.204.104.128-65.204.104.143
66.92.180.48-66.92.180.63
67.200.105.48-67.200.105.51
65.201.208.24-65.201.208.31
66.220.144.0-66.220.159.255
69.171.224.0-69.171.255.255
74.119.76.0-74.119.79.255
204.15.20.0-204.15.23.255
173.252.64.0-173.252.127.255
67.220.103.240-67.220.103.255"],
            [12,1,"Google IPs","70.32.128.0-70.32.159.255
70.89.39.152-70.89.39.159
173.194.0.0-173.194.255.255
65.167.144.64-65.167.144.79
65.170.13.0-65.170.13.15
63.166.17.128-63.166.17.255
65.171.1.144-65.171.1.159
64.9.224.0-64.9.255.255
63.161.156.0-63.161.156.255
199.87.241.32-199.87.241.63
65.214.112.96-65.214.112.127
66.192.134.32-66.192.134.47
65.196.235.32-65.196.235.47
64.128.207.160-64.128.207.175
63.84.190.224-63.84.190.255
65.221.133.176-65.221.133.191
65.223.8.48-65.223.8.63
65.211.194.96-65.211.194.111
65.214.255.96-65.214.255.111
64.124.229.168-64.124.229.175
209.249.73.64-209.249.73.71
64.124.112.24-64.124.112.31
46.170.0.0-46.170.128.255
216.239.32.0-216.239.63.255
70.90.219.0-70.90.219.255
64.68.90.1-64.68.90.255
64.233.160.0-64.233.191.255
66.102.0.0-66.102.15.255
66.249.64.0-66.249.95.255
72.14.192.0-72.14.255.255
74.125.0.0-74.125.255.255
209.85.128.0-209.85.255.255"],
            [13,3,"Google UAs","googlebot
adsbot
gsa-crawler
mediapartners"],
            [14,1,"Websense. Inc","208.80.192.0-208.80.199.255
192.132.210.0-192.132.210.255
206.169.148.0-206.169.148.255
204.15.64.0-204.15.71.255"],
            [15,3,"Bot UAs","kw-lp-suggest
Python
alexa
askjeeves
bluecoat
fast
firefly
froogle
google
infoseek
inktomi
looksmart
nationaldirectory
rabaz
scooter
sogou
spade
tecnoseek
teoma
webbug
galaxy.com
zyborg
bot
OPtional
uberleet.org"]
        ]);
    }


    /**
     * @inheritdoc
     */
    public function down()
    {
        $this->dropTable('{{%mts_campaign}}');
        $this->dropTable('{{%mts_offer}}');
//        $this->dropTable('{{%mts_campaign_offer_index}}');
        $this->dropTable('{{%mts_landingpage}}');
//        $this->dropTable('{{%mts_campaign_landingpage_index}}');
//        $this->dropTable('{{%mts_landingpage_offer_index}}');
        $this->dropTable('{{%mts_entry_index}}');
        $this->dropTable('{{%mts_cloak}}');
        $this->dropTable('{{%mts_redirect}}');
        $this->dropTable('{{%mts_click}}');
        $this->dropTable('{{%mts_network}}');
        $this->dropTable('{{%mts_trafficsource}}');
        $this->dropTable('{{%mts_browser}}');
        $this->dropTable('{{%mts_browserversion}}');
        $this->dropTable('{{%mts_carrier}}');
        $this->dropTable('{{%mts_isp}}');
        $this->dropTable('{{%mts_continent}}');
        $this->dropTable('{{%mts_country}}');
        $this->dropTable('{{%mts_devicetype}}');
        $this->dropTable('{{%mts_brand}}');
        $this->dropTable('{{%mts_model}}');

        $this->dropTable('{{%mts_os}}');
        $this->dropTable('{{%mts_osversion}}');
        $this->dropTable('{{%mts_referer}}');
        $this->dropTable('{{%mts_refererdomain}}');
        $this->dropTable('{{%mts_resolution}}');
        $this->dropTable('{{%mts_size}}');
        $this->dropTable('{{%mts_useragent}}');
    }
}
