<?php

namespace backend\models;

use Yii;
use backend\models\EntryIndex;
use backend\models\EntryIndexEx;

/**
 * This is the model class for table "{{%mts_landingpage}}".
 *
 * @property integer $id
 * @property string $name
 * @property string $redirectUrl
 * @property integer $clicks
 * @property double $cost
 * @property double $income
 * @property integer $conversion
 * @property integer $active
 */
class Landingpage extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%mts_landingpage}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'redirectUrl'], 'required'],
            [['click','lead'], 'integer'],
            [['cost', 'income'], 'number'],
            [['name', 'redirectUrl'], 'string', 'max' => 255],
        ];
    }

    public static function dropDownItems()
    {
        $items = Yii::$app->cache->get(['landingpageList']);
        if ($items === false) {
            $query = static::find();

            $list = $query->asArray()->all();
            $items = [];
            foreach ($list as $item){
                $items[$item['id']] = $item['name'];
            }

            Yii::$app->cache->set(['landingpageList'], $items, 0);
        }
        return $items;
    }

//    public function  afterSave($insert, $changedAttributes)
//    {
//        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
//        Yii::$app->cache->delete(['landingpageList']);
//    }

    public function getOffers()
    {
        return $this->hasMany(EntryIndex::className(), ['fromID' => 'id'])->onCondition(['type' => EntryIndex::LP_2_OFFER]);
      
    }
    public function getLps()
    {
        return $this->hasMany(EntryIndexEx::className(), ['fromID' => 'id'])->onCondition(['type' =>EntryIndex::LP_2_LP]);

    }

    public function getActiveOffers()
    {
        return $this->hasMany(EntryIndex::className(), ['fromID' => 'id'])->onCondition(['inactive' => 0,'type'=>[EntryIndex::LP_2_OFFER,EntryIndex::LP_2_LP]]);

    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('tracking', 'ID'),
            'name' => Yii::t('tracking', 'Name'),
            'redirectUrl' => Yii::t('tracking', 'Redirect Url'),
            'click' => Yii::t('tracking', 'Clicks'),
            'cost' => Yii::t('tracking', 'Cost'),
            'income' => Yii::t('tracking', 'Income'),
            'lead' => Yii::t('tracking', 'Leads'),
        ];
    }


}
